### PR TITLE
Fix issue parsing relative imports in stylus files

### LINKED ISSUE #52: Error parsing stylus that contains imports
## Description
If a Vue template contains a stylus that has an import to an external stylus file, the test suite requiring this file fails with the message:

```shell
failed to locate @import file path/to/stylus/file/in/vuetemplate
```

vue-jest-stylus-issue

## To reproduce the issue
`git clone https://github.com/mdvorscak/vue-test-utils-jest-example.git && npm i && npm run test`

### PR DESCRIPTION
**Pull request by mdvorscak**
This PR fixes #52

### CODE REVIEW

File: lib/process.js [hunk 1]
```diff
@@ -28,13 +28,14 @@ function processScript (scriptPart) {
   return compileBabel(scriptPart.content)
 }
 
-function processStyle (stylePart) {
+function processStyle (stylePart, path) {
   if (!stylePart) return {}
 
   let cssCode = stylePart.content
   if (/^styl|stylus$/.test(stylePart.lang)) {
+    const vuePath = join(path, '..')
```
Comment (eddyerburgh) [inline lib/process.js]: Can you use process.cwd for the path? Like in vueify—https://github.com/vuejs/vueify/blob/master/lib/compilers/stylus.js#L14

**Comment by mdvorscak** [comment]
Thanks for taking a look, I also changed the directory resolution to be clearer. And as a result renamed the path variables to filePath to avoid confusion.

**Comment by eddyerburgh** [comment]
Thanks 😀
